# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/reference/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#jobs-overview & https://circleci.com/docs/reference/configuration-reference/#jobs
jobs:
  sonar-scan:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/guides/execution-managed/executor-intro/ & https://circleci.com/docs/reference/configuration-reference/#executor-job
    docker:
      - image: cimg/node:18.20  # Includes Node.js, npm, and OpenJDK 17
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:current

    # Add steps to the job
    # See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#steps-overview & https://circleci.com/docs/reference/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout

      - run:
          name: Change directory to project folder
          command: cd INSY7314_POE

      # Restore cache
      - restore_cache:
          keys:
            - v1-node-deps-{{ checksum "INSY7314_POE/frontend/package-lock.json" }}
            - v1-node-deps-

      # Install frontend dependencies
      - run:
          name: Install frontend Node.js dependencies
          command: |
            cd INSY7314_POE/frontend
            if [ -f package-lock.json ]; then
              npm install
            fi

      # Save cache
      - save_cache:
          paths:
            - INSY7314_POE/frontend/node_modules
          key: v1-node-deps-{{ checksum "INSY7314_POE/frontend/package-lock.json" }}

      # Install SonarQube Scanner
      - run:
          name: Install SonarQube Scanner
          command: |
            curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
            unzip sonar-scanner.zip -d $HOME
            export PATH=$HOME/sonar-scanner-5.0.1.3006-linux/bin:$PATH

      # Run SonarQube scan
      - run:
          name: Run SonarQube Scan
          command: |
            cd INSY7314_POE
            $HOME/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner \
              -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
              -Dsonar.organization=${SONAR_ORG} \
              -Dsonar.host.url=${SONAR_HOST_URL} \
              -Dsonar.login=${SONAR_TOKEN} \
              -Dsonar.sources=frontend,backend \
              -Dsonar.sourceEncoding=UTF-8
          name: "Say hello"
          command: "echo Hello, World!"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/guides/orchestrate/workflows/ & https://circleci.com/docs/reference/configuration-reference/#workflows
workflows:
  scan-workflow:
  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - sonar-scan
      - say-hello
